### ISSUE TITLE
Details page bug

### ISSUE THREAD

**Issue by jovialcore** [jovialcore/whatcompstack-FE#26]
On refresh of details page (e.g https://whatcompanystack.com/details/sippylife ), the page loads without any content only header and footer will show. 
If you check the console you will see a null error message. 

![Screenshot from 2024-01-04 12-36-01](https://github.com/jovialcore/whatcompstack-FE/assets/32295501/bffeb51a-1f5b-4f50-9abc-577c53862944)

**Comment by jovialcore** [comment]
I should be closing this bug soon cos the latest migration to nuxt should fix this

**Comment by danieliheonu** [comment]
Let's not close it till we confirm it

**Comment by jovialcore** [comment]
https://deploy-preview-33--bejewelled-crepe-4f96c8.netlify.app/details/paystack 

You can check here

**Comment by jovialcore** [comment]
its up now

**Comment by jovialcore** [comment]
https://github.com/jovialcore/whatcompstack-FE/pull/33

**Comment by danieliheonu** [comment]
Lgtm
